# Generated by Django 5.2 on 2025-05-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto_portada',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_portada/'),
        ),
    ]
