# Generated by Django 5.2 on 2025-05-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfil_foto_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='autos_favoritos',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, default='fotos_perfil/default.png', null=True, upload_to='fotos_perfil/'),
        ),
    ]
