# Generated by Django 5.2 on 2025-05-19 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AddField(
            model_name='publicacion',
            name='categoria',
            field=models.CharField(choices=[('f1', 'Fórmula 1'), ('rally', 'Rally'), ('tuning', 'Tuning'), ('clasicos', 'Clásicos'), ('supercar', 'Supercars'), ('electrico', 'Eléctricos'), ('motorsport', 'Motorsport'), ('otros', 'Otros')], default='otros', max_length=50),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='publicaciones.publicacion')),
            ],
            options={
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
