# Generated by Django 5.2 on 2025-05-19 22:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_alter_publicacion_options_publicacion_categoria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='publicaciones_gustadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
